const subData = [
    {
        subName: "Feel Good" ,
        subBread: ["Whole"],
        subProtein: ["Prosciutto"],
        subCheese: ["Gruyere cheese"],
        subRelish: ["Spinich"], 
        subSauce: ["Famous Sub Sauce"],
        subPrice: 120,
    },
    {
        subName: "Sublicious" ,
        subBread: ["Baguette"],
        subProtein: ["Pulled Pork"],
        subCheese: ["Gruyere"],
        subRelish: ["red Onion sliced"], 
        subSauce: ["Famous Sub Sauce, Barbeque"],
        subPrice: 100,
    },
    {
        subName: "Holy Shrimp!" ,
        subBread: ["baguette"],
        subProtein: ["Fried Shrimp"],
        subCheese: [""],
        subRelish: ["Red Onion Sliced"], 
        subSauce: ["Famous Sub Sauce"],
        subPrice: 90,
    },
    {
        subName: "Le Frique" ,
        subBread: ["baguette"],
        subProtein: ["Fried Chicken"],
        subCheese: ["Gruyere cheese"],
        subRelish: ["Red Onion Sliced"], 
        subSauce: ["Famous Sub Sauce, Barbeque"],
        subPrice: 80,
    },
    {
        subName: "Fried but Light",
        subBread: ["Brioche"],
        subProtein: ["Fried Shrimp"],
        subCheese: ["Gruyere Cheese"],
        subRelish: ["Tomato, Rocket, Jalapeño"], 
        subSauce: ["Famous Sub Sauce"],
        subPrice: 85,
    },
    {
        subName: "A Little Smoke",
        subBread: ["Whole"],
        subProtein: ["Turkey Sliced"],
        subCheese: ["Gruyere Cheese"],
        subRelish: ["Red Onion, Pickles, Jalapeño"], 
        subSauce: ["Barbeque, Famous Sub Sauce"],
        subPrice: 85,
    },
    {
        subName: "Mo' Beef Mo' Flava",
        subBread: ["Baguette"],
        subProtein: ["Sliced Beef"],
        subCheese: ["Gruyere Cheese"],
        subRelish: ["Tomato, Red Onion Sliced,"], 
        subSauce: ["Famous Sub Sauce"],
        subPrice: 90,
    },
    {
        subName: "Le Chick",
        subBread: ["Baguette"],
        subProtein: ["Braaied Chicken"],
        subCheese: ["Gruyere Cheese"],
        subRelish: ["Tomato, Rocket, Red Onion"], 
        subSauce: ["Famous Sub Sauce"],
        subPrice: 95,
    },

]